# Generated by Django 5.1.3 on 2024-11-09 15:08

import django.db.models.deletion
import features.boarding_house.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_rename_city_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_house_name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('street', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.barangay')),
                ('municipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.municipality')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.province')),
            ],
        ),
        migrations.CreateModel(
            name='BoardingHouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=features.boarding_house.models.boarding_house_image_path)),
                ('boarding_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boarding_house.boardinghouse')),
            ],
        ),
    ]
