# Generated by Django 5.1.3 on 2024-11-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boarding_house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardinghouse',
            name='street',
        ),
    ]
