# Generated by Django 5.1.3 on 2024-11-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('authentication', '0002_rename_city_user_province'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Province',
        ),
        migrations.RenameField(
            model_name='municipality',
            old_name='city',
            new_name='province',
        ),
    ]
