# Generated by Django 5.1.3 on 2024-11-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('boarding_room', 'Boarding Room'), ('boarding_house', 'Boarding House')], default='boarding_room', max_length=20),
        ),
    ]
