# Generated by Django 5.1.3 on 2024-11-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0002_booking_created_at_booking_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
