# Generated by Django 5.1.3 on 2024-11-26 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0006_alter_boardinghouse_landlord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingroom',
            name='capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
