# Generated by Django 5.1.3 on 2024-11-26 04:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0006_alter_boardinghouse_landlord_and_more'),
        ('rating', '0002_rating_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'boarding_room')},
        ),
    ]
